### ISSUE TITLE
Placeholder suggestions for photos for co-authors

### ISSUE THREAD

**Issue by spcanelon** [LizHareDogs/iwdba2021#1]

**Comment by spcanelon** [comment]
@LizHareDogs, something I've done in the past is styled a slide to have essentially a narrow left column for the person's photo and a wide right column that compliments it that includes the person's name, title, etc. This might be a good option because it lets you list the people as you move down the slide. This vertical layout, I think, is more flexible and future-proof than arranging co-authors horizontally. What do you think?

**Comment by LizHareDogs** [comment]
Hi Silvia, Thanks for all your work on this! 

I'm thinking it's probably not necessary to have photos of  myself or coauthors. We didn't do this in the psat, and I Think it might just take up too much space.  

I have to record this talk so I will be visible alongside the screenshare on Zoom.

I'm also not sure we'll need everybody's contact info. They are all also presenting, I think, and the info will be available in the directory for the meeting.

**Comment by spcanelon** [comment]
I think this is addressed by pull request https://github.com/LizHareDogs/iwdba2021/pull/10
