### ISSUE TITLE
Add link to slides to repo page

### ISSUE THREAD

**Issue by spcanelon** [LizHareDogs/iwdba2021#14]
Hi @LizHareDogs! I recommend adding a link to your slides somewhere on your repo so that people can find them. You could add a link in the ReadMe, and/or in the About section of your repo. For the latter, you can follow these steps:

1. Find the section on the main page of your repo that is titled "About." It is located to the right of the main pane that contains the files, commits, etc.
2. To the right of the "About" heading is a gear icon that I think should read as "Edit repository metadata." Click there and a new dialogue box will open that allows you to edit or add more repository details
3. There is a field titled "Website" where you could add the link to your slides: https://lizharedogs.github.io/iwdba2021

**Comment by LizHareDogs** [comment]
Thank you @spcanelon for the directions. This has been done.
