### ISSUE TITLE
Slide 3: stray HTML

### ISSUE THREAD

**Issue by spcanelon** [LizHareDogs/iwdba2021#5]

**Comment by LizHareDogs** [comment]
Found error serendipitously - there was a stray tab before

.left-column

and the . has to be in the first column.

**Comment by spcanelon** [comment]
Great! On the topic of columns, I recommend using `.pull-left[]` and `.pull-right[]` classes if you want to pull some content to the left and some to the right of the slide. 

The `.pull` classes pull your content to the left or right 45% of the slide space. Whereas `.left-column[]` pulls content to the left 20% and `.right-column[]` to the right 60%, something like that. This gives the appearance of a thin column on the left and a wide column on the right, but they aren't styled the same way. These classes are a bit opinionated like that, and it's rare when I see them used IRL.

**Comment by LizHareDogs** [comment]
Oh, thanks for explaining this! I looked these commands up in the css folder but your explanation is helping me more!

Will go see where I should swap in .pull-left[] and .pull-right[].

**Comment by spcanelon** [comment]
I found one more spot that still needs updating to .pull-left[] and .pull-right[] -- slide 22!

**Comment by LizHareDogs** [comment]
Thanks-- that was one that I wasn't sure if I should change, for some reason. So you decided for me :)

Liz
