### ISSUE TITLE
Slide 11: confirm table placement

### ISSUE THREAD

**Issue by spcanelon** [LizHareDogs/iwdba2021#7]
> does table appear to the right of the text?

**Comment by spcanelon** [comment]
Yes a small table appears on the right half of the slide. And now it also looks level with the text, before the pull request it looked a little bit higher

**Comment by spcanelon** [comment]
If you wanted to, you could get away with combining slide 9 about the BCL and slide 10 with the BCL Scoring table into one slide using pull-left and pull-right. The BCL slide has 3 brief bullets and the BCL scoring table is narrow, maybe 15 characters (2-3 words) wide.

**Comment by LizHareDogs** [comment]
Thanks! I will probably consolidate the slidesas you suggest. 

The ridiculous thing is that the organizers have requested for us to minimize words and maximize pictures (ugh!) so I was trying to keep the slides pretty sparse. But you are right that there's plenty of room there.

**Comment by LizHareDogs** [comment]
? but I already left the comment; still learning here :)
